### ISSUE TITLE
Feedback before Code Review 2

### ISSUE THREAD

**Issue by adrhill** [viktorlorentz/Cluster.jl#14]
Hi all, 

here's some quick feedback before the second code review session next week.
I'm opening this as a single issue to not spam your repository, which already looks really good!

My notes:

* Documentation 
    * It would be nice to have a second doc page with a full example and visualizations
       * you have a great README! Unfortunately, the Binder notebook doesn't work. Maybe this could be included in the documentation instead?
       *  Rewriting your example to a standard `.jl` script would allow you to use [Literate.jl](https://fredrikekre.github.io/Literate.jl/v2/) to convert it into both a Pluto notebook and a Markdown file.
    * nice API Reference!
    * examples in docstrings could be written as `julia-repl` blocks. Include their outputs to make them more informative!
    * you could use [DocStringExtensions.jl](https://docstringextensions.juliadocs.org/stable/) to generate type signatures which are always up to date (see example [here](https://github.com/adrhill/SparseConnectivityTracer.jl/blob/34e6bec545ed6d8c254c749fe81a4674807bfed4/src/tracers.jl#L70-L89)) 
        * your docstring on `KMeans` is outdated and indicates `mode::Symbol`, where the code says `mode::String` (in general, `Symbol` is the more "Julian" choice here)
        * your docstring on `init_centroids` documents type restrictions which the code doesn't have

* Code
    * use `eachrow`/`eachcol`/`eachslice` wherever possible, e.g. here:  https://github.com/viktorlorentz/Cluster.jl/blob/c6293af217a136297f81b2a3d92e97511f80a2ea/src/Cluster.jl#L247

* Tests
    * Great code coverage and great that you test errors as well! :)
    * Would be nice to have some analytical reference tests, if possible (maybe you could fix the RNG?)

**Comment by viktorlorentz** [comment]
Thank you very much for the detailed feedback. We tried to integrate it as much as possible.
