### ISSUE TITLE
Decision Boundary colors don't match cluster colors

### ISSUE THREAD

**Issue by thomasfischer11** [viktorlorentz/Cluster.jl#21]
I played around a bit with the parameters in the example notebook and the colors of the areas in the decision boundary plot sometimes don't match with the colors of the datapoints of the corresponding clusters.
Eg for parameters:
Seed:
0
Samples per class:
24
Features/ Dimensions:
2
Classes:
5
Spread of cluster:
5.0)
Clustering algorithm:
kmeans

**Comment by viktorlorentz** [comment]
Fixed. Thanks for your feedback.
